### ISSUE TITLE
Maybe advise "pip install --user"

### ISSUE THREAD

**Issue by felixhummel** [srsudar/eg#15]
Hi,

I always look for ways to advertise `pip install --user` and I believe `eg` to be very user specific, so maybe it makes sense to change the README to say the following:

# Installation
## With `pip` For Your User

    pip install --user
    echo 'PATH=$PATH:$HOME/.local/bin' >> $HOME/.bashrc
    exec $SHELL

What do you think?

Cheers,
  Felix

PS: For those interested here is the talk where I got this idea from: [Youtube](https://www.youtube.com/watch?v=eLPiPHr6TVI#t=6m51s) / [PyVideo](http://pyvideo.org/video/2631/python-packaging-simplified-for-end-users-app-d)

**Comment by srsudar** [comment]
Interesting. That looks like a very useful video. Most of my `pip`/pypi knowledge has come from googling and trial and error, so I'll have to watch it in its entirety.

I vote to keep the installation example without the `--user` flag. Most installation examples I see omit the `--user` flag, for better or worse, and I think there's something to be said for consistency. If I was installing something, having to edit my `.bashrc` for a basic `pip install` might scare me off (I also use zsh, so I'd get into trouble following that example directly, and on my mac I'd have to do it to `.bash_profile`!).

The video claims that your home directory is an entry on `sys.path`, implying that installation via the `--user` flag should work. It's not on my `sys.path`, however (although exactly why, I'm not sure), which is why I think your `echo` statement would be necessary.

I think the `--user`-less `pip install` example is a good base case that power users can expand upon to decide if they want to install just to their user directory.

As for `eg` being user-specific, to a certain extent I think you're right. In general, however, I imagine user-defined extension examples will be stored in user-specific directories, so I think a global install would still be ok.
