### ISSUE TITLE
Merge with tldr-pages?

### ISSUE THREAD

**Issue by ProgVal** [srsudar/eg#4]
I'm not sure this is appropriate, but there is another project that looks very similary to this one: https://github.com/tldr-pages/tldr

Maybe you could join efforts?
Or is there a difference that I didn't catch?

**Comment by srsudar** [comment]
That is an interesting idea. I know of three other tools that do similar things:
* `bro`
* `cheat`
* `tldr`

I'm not a fan of the brogrammer theme of `bro`, and it's not important to me that I can vote on which examples are useful. It's a very cool idea, but a lot of the output is for voting, which isn't something I particularly value.

`cheat` is another interesting one, although (at least on my machine) it doesn't colorize output, and `cheat` takes an approach more of "alter" (by updating the defaults) rather than "augment" (create new examples) for extension. I prefer the approach I took with `eg`, where by default the examples it ships with stay intact--although you can overwrite them if you want--and it encourages you instead to create your own custom examples.

`tldr` I just didn't know about until a week or so ago. I haven't had a chance to look into it in depth yet to see if there are meaningful differences. From the README it looks cool. When I get a chance I'm going to do a more meaningful comparison and see what makes sense. A full merge is unlikely, I would say, as they've apparently had something going on for quite a while and are likely to see `eg` as an upstart. But at least I'll be better able to answer your question.

Overall, I'm pleased there are so many good options. =)

**Comment by srsudar** [comment]
I've looked into `tldr`, and it has some awesome things going for it. It works on lots of platforms and with lots of languages (go, python, node, even the web--the value this adds is up to you, but it's neat). They also have a larger library of commands, which makes sense as it's an older project. Eventually I hope `eg` will have a similar-sized library.

Another thing they seem to be trying to solve, which I punted on when designing `eg` (but have continued to think about), is supporting multiple platforms. Some flags to `ps` and `top`, for instance, only work on unix. Some, like `brew`, aren't likely needed on unix, while `free` doesn't exist on OSX. `tldr` looks to have sections for each of these, while `eg` currently keeps them all at the same level. This means OSX users can `eg free`, even though they can't install free on their machine. I haven't thought of any reasons this will be a deal breaker in the future, but it's something I've thought about.

I'm happy with the way `eg` is currently set up, however. I feel like it aims for `tldr`-style examples in the first section, and then moves to more detail, which none of the `tldr` pages I've looked at have. `eg` is also intended to be customizable, which `tldr` does not seem to be. `eg` feels to me like an example-driven supplement to man pages, including explanatory text as necessary, rather than purely examples. 

I'd be curious to hear if people think this approach is flawed, or if they have ideas for how to improve it, but I think `eg` and the tools above have different approaches, all valid.

**Comment by reorx** [comment]
What I think of the difference between `tldr` and `eg` is that `tldr` is just a cheat sheet of most commonly used examples, whereas `eg` is a more friendly & readable version of the man page, it provides more details than `tldr`.

In the last year, I've been doing DevOps jobs a lot, I tried `tldr`, it is useful at the first glance, but I found myself always end up looking into man page for details about options and different usages. After using `eg` for a while, I found there's no need for man page in most cases, I think `eg` reaches a great balance between “quick looking” and “informative”. For people who seldom use the command line but sometimes have to, I recommend `tldr`, for programmers and people use command line every day, I recommend `eg`.

Some further thoughts about being a programmer to look up command usage quickly, I think the best thing is the notes taken by yourself, `eg` is, of course, both condensed and expressive, but that' not enough. I believe the examples of `eg` come from @srsudar's notes, or at lease been fully read and understood by him, so `eg` is best fit for @srsudar, not any one else :D. Since I also have some sort of notes like that (see image below), I hope there would be a tool that can read and search from a local dataset of my notes (in a certain format) and present it gracefully, just as how `eg` do with its examples.

![screen shot 2016-01-11 at 16 48 57](https://cloud.githubusercontent.com/assets/405972/12229615/73febf9a-b884-11e5-878a-6738ad9e4b4d.png)

**Comment by srsudar** [comment]
Yeah that is an interesting point. Glad to hear it's been useful.

@reorx are you aware of `eg`'s support of including your own notes? You have to specify the correct directory and name the file appropriately, but you could include your own notes without too much trouble using that feature.

**Comment by reorx** [comment]
@srsudar that's great, I just aware it! Now most of my notes could be used by eg seamlessly. Some of my notes are a bunch of command usages together, like the one called `Bash & OS X`, I have record the examples of `date`, `lsof`, `dscacheutil` etc. I'm considering adding an option for eg, with that option it can search through this kind of notes and show only examples of a certain command.

**Comment by srsudar** [comment]
`eg` will find any file you name and place appropriately, so if you wanted to have `osx.md` and then do `eg osx` it would work. `eg --list` will show you all your options and indicate if the source is default, user-defined, or both.

There are a couple open PRs that I are on my list of merging. [One](https://github.com/srsudar/eg/pull/41) is for `date`. I'll make a note on that about status, but it will be happening soon.

**Comment by reorx** [comment]
That's good enough, thanks :P
