### ISSUE TITLE
Better and convenient custom functionnality

### ISSUE THREAD

**Issue by arnaudmm** [srsudar/eg#48]
Hey!

Why not create a custom dir and include its content by default ?
And add it to .gitigore

This way we can git clone, create our very custom in this folder, commit them to our personnal repo, and from time to time git pull this original repo to get updates.

What do you think about it ?

**Comment by srsudar** [comment]
That is an interesting idea. Users that clone the repo (as opposed to installing via pip) could already do something like this with some git trickery. If you made a `custom-dir` in the repo and added a `.gitignore` to that directory with `*` to ignore everything, it would allow you to keep both in the same place.

This would still have to be configured using an `.egrc`, though, so that eg would know where to look. You're suggesting that we would look for a `custom-dir` of some sort in the base directory by default?

**Comment by arnaudmm** [comment]
Yes exactly! If you do that, we don't have to do anything :
-customdir already created
-already ignored in gitignore
-no need for an egrc configuration

Would be great!

**Comment by srsudar** [comment]
Sorry for the epic delay (five years!). I think you can already replicate this behavior on your own easily enough that I'm not inclined to add it. You can use the git trick I suggested above, add your custom examples to whatever repo you use to version your dotfiles (this is what I do), or even just edit the examples that ship with `eg` and still perform merges.
